### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by pwab** [TwistedTwigleg/Godot_GSOC_2020_Project#1]
So today I was able to build the 3D side of the IK PRs and get some quick look into it. Thanks for the jaw drops. 🤯

## Just some general feedback

As always Godot crashed at first start of the project but I felt that it was quite stable. Even while starting and stopping Test_9 it kept calm and just showed me some warnings and errors. Here is a little collection of those messages that I got (I removed the duplicates):

### Test_03

```
WARNING: Cannot update cache: modification is not properly setup!
     at: SkeletonModification3DCCDIK::update_target_cache (scene\resources\skeleton_modification_3d.cpp:793)
WARNING: Cannot update cache: modification is not properly setup!
     at: SkeletonModification3DCCDIK::update_tip_cache (scene\resources\skeleton_modification_3d.cpp:816)
```

### Test_05

```
ERROR: Cannot auto calculate joint length: modification is not setup!
   at: (scene\resources\skeleton_modification_3d.cpp:1452)
WARNING: Cannot update cache: modification is not properly setup!
     at: SkeletonModification3DFABRIK::update_joint_tip_cache (scene\resources\skeleton_modification_3d.cpp:1305)
WARNING: Cannot update cache: modification is not properly setup!
     at: SkeletonModification3DLookAt::update_cache (scene\resources\skeleton_modification_3d.cpp:509)
WARNING: Cannot update cache: modification is not properly setup!
     at: SkeletonModification3DJiggle::update_cache (scene\resources\skeleton_modification_3d.cpp:1810)
WARNING: Cannot setup SkeletonModificationStack3D: no skeleton set!
     at: SkeletonModificationStack3D::setup (scene\resources\skeleton_modification_3d.cpp:84)
```

### Test_09

```
WARNING: Cannot update target cache: modification is not properly setup!
     at: SkeletonModification3DTwoBoneIK::update_cache_target (scene\resources\skeleton_modification_3d.cpp:2369)
WARNING: Cannot update tip cache: modification is not properly setup!
     at: SkeletonModification3DTwoBoneIK::update_cache_tip (scene\resources\skeleton_modification_3d.cpp:2392)
WARNING: Cannot update pole cache: modification is not properly setup!
     at: SkeletonModification3DTwoBoneIK::update_cache_pole (scene\resources\skeleton_modification_3d.cpp:2415)
WARNING: Cannot update tip cache: modification is not properly setup!
     at: SkeletonModification3DTwoBoneIK::update_cache_tip (scene\resources\skeleton_modification_3d.cpp:2392)
ERROR: Pole cache is out of date. Attempting to update...
   at: SkeletonModification3D::_print_execution_error (scene\resources\skeleton_modification_3d.cpp:316)
```

Apart from that all scenes worked fine. I guess.

## Make testing easier

One aspect that could make the testing easier would be to make sure the targets children are not selectable (with this little editor function I'm not sure how to call). So the targets can be clicked and moved without only moving their meshes.

## Test_01

The robot in Test_01 moves amazingly smooth. Only the joints meshes don't fit to their skeletons counterpart. A cylinder in a hole should only be able to rotate if it is mounted from both sides. So it is more like a robot with ball joints right now. Maybe this could be handled by some joint constraints?

## Test_03

The `Simple_Test_Rigs` in Test_03 are a bit confusing. What are they supposed to move like?

## Test_04_FABRIK

This was interesting. If the target is near enough the base the armature can find its pose and that's it. But if the target is moved a bit away it starts to wave around the target. Almost like it is seaching for the right orientation (not position) of the tip but couldn't find it. This behavior can escalate and leads to a massive oscillation (which is sometimes amplified and sometimes damped). Here's some footage:

![Test_04_FABRIK](https://user-images.githubusercontent.com/19271185/93258813-31778a80-f79f-11ea-97f5-b34324d65733.gif)

---

I'm going to test this further if I find some time. Maybe tomorrow or at the weekend.

**Comment by TwistedTwigleg** [comment]
> So today I was able to build the 3D side of the IK PRs and get some quick look into it. Thanks for the jaw drops. 🤯

Thanks! 😁 

> As always Godot crashed at first start of the project but I felt that it was quite stable. Even while starting and stopping Test_9 it kept calm and just showed me some warnings and errors. Here is a little collection of those messages that I got (I removed the duplicates):

Hmm, some of those errors are likely that the resource doesn't realize it hasn't been setup yet, so it cannot access some of the data it needs from the Skeleton3D node. I'll look into it.

> One aspect that could make the testing easier would be to make sure the targets children are not selectable (with this little editor function I'm not sure how to call). So the targets can be clicked and moved without only moving their meshes.

Good idea! I was constantly having to deal with that. I think there is a editor setting that can be selected to make it where child nodes cannot be moved in the 3D view.

> The robot in Test_01 moves amazingly smooth. Only the joints meshes don't fit to their skeletons counterpart. A cylinder in a hole should only be able to rotate if it is mounted from both sides. So it is more like a robot with ball joints right now. Maybe this could be handled by some joint constraints?

Thanks! It should be doable to restrict the rotation to a single plane, which should make it act more like a hinge and less like a ball-joint. I *think* it should be possible now through the restrict rotation to plane setting. I'll look into it regardless.

> The Simple_Test_Rigs in Test_03 are a bit confusing. What are they supposed to move like?

They were just for testing angle constraints, and because of that they're kinda... meh. I haven't worked on the simple_test_rigs in quite awhile, just the robotic arm in Test_03. Initially they were also for testing the different rotation modes, which is why there are two of them, but I later removed the rotation modes as it wasn't strictly CCDIK and I thought it would be confusing. They can, and should, probably be removed.

> This was interesting. If the target is near enough the base the armature can find its pose and that's it. But if the target is moved a bit away it starts to wave around the target. Almost like it is seaching for the right orientation (not position) of the tip but couldn't find it. This behavior can escalate and leads to a massive oscillation (which is sometimes amplified and sometimes damped). Here's some footage:

Hmm, that's not good. I think it is likely caused because either A: I removed the forward pass (since it didn't appear to be doing anything) or B: there is something wrong in the algorithm. I knew the FABRIK joint would wiggle/oscillate when the target is *just* out of reach, but I didn't realize it also applies to when it is just farther away from the root as well. I'll update my TODO with this information.

> I'm going to test this further if I find some time. Maybe tomorrow or at the weekend.

Thanks! I really appreciate you going through and giving me valuable feedback! 😄

**Comment by TwistedTwigleg** [comment]
Everything mentioned in this issue should be fixed now in the latest commit to the 3D IK PR and the last two commits to this repository! :tada: 

Closing this issue for now, but if you find anything else or the issues reoccur (or still occur for you), please let me know and I'll open the issue back up. Thanks again for the report and feedback!

**Comment by pwab** [comment]
Great! I'll give it a try asap.
