### ISSUE TITLE
Headsup: Trying to upgrade to godot 4 latest

### ISSUE THREAD

**Issue by fire** [TwistedTwigleg/Godot_GSOC_2020_Project#2]
Tracker

* [x] Updated to latest Godot 4
* [x] Use godot demo projects folder structure
* [x] Update test folders with names

**Comment by fire** [comment]
@TwistedTwigleg I'm having trouble finding the proper parameters for each ik.

**Comment by TwistedTwigleg** [comment]
Which IK modifiers and properties are having issues? It should, for the most part, be ready to go by just assigning the bones, though sometimes you have to save, close, and then reopen the scene before it will work (so initialization code can run).

If you want, I can download your fork and make a PR with the correct parameters, if that would help.

**Comment by fire** [comment]
Go ahead!

**Comment by fire** [comment]
The problem was I wasn't able to mind read what the original parameters were. It's ok to imagine new paramters.

**Comment by TwistedTwigleg** [comment]
Gotcha. Well, I don't remember what the original ones were either, so it would be a matter of inputting in the parameters that give the best visual results and seeing how it looks.

I'll try to download the fork and take a look when I have time.

**Comment by TwistedTwigleg** [comment]
@fire - I added the modifications back in #4 , so you should be able to test/merge that commit into your branch and then all of the IK modifications should be setup. I had to make a few minor changes here and there, but it was mostly just setting up the IK modifications themselves.

The only scene I couldn't get totally working was the last one, the FPS example, as the animation player wasn't working due to a bug with the AnimationPlayer node itself, from what I can gather. It might be because I'm using an older version of Godot 4.0 though. I will test it later with a daily build and see if that fixes the issue (and then merge #4, assuming no additional changes are needed to fix the FPS issue)
